### Tensor常见的形式有哪些

* 0: scalar
* 1: vector
* 2: matrix
* 3: n-dimensional tensor

In [1]:
import torch
from torch import tensor

### Scalar

通常就是一个数值

In [2]:
x = tensor(42.)
x

tensor(42.)

In [3]:
x.dim()

0

In [4]:
2 * x

tensor(84.)

In [5]:
x.item()

42.0

## Vector

例如： `[-5., 2., 0.]`，在深度学习中通常指特征，例如词向量特征，某一维度特征等
$$\vec{v} = \left[ v_1, v_2, \ldots, v_n \right]$$

In [6]:
v = tensor([1.5, -0.5, 3.0])
v

tensor([ 1.5000, -0.5000,  3.0000])

In [7]:
v.dim()

1

In [8]:
v.size()

torch.Size([3])

### Matrix
- 一般计算的都是矩阵，通常都是多维的

In [17]:
M = tensor([[1., 2.], [3., 4.]])
M

tensor([[1., 2.],
        [3., 4.]])

In [18]:
M.matmul(M)

tensor([[ 7., 10.],
        [15., 22.]])

In [19]:
tensor([1., 0.]).matmul(M)

tensor([1., 2.])

In [20]:
M * M

tensor([[ 1.,  4.],
        [ 9., 16.]])

In [21]:
tensor([1., 2.]).matmul(M)

tensor([ 7., 10.])

## 几种形状的Tensor

![Scalar, vector, matrix, tensor - a drawing by Tai-Danae Bradley](https://uploads-ssl.webflow.com/5b1d427ae0c922e912eda447/5cd99a73f8ce4494ad86852e_arraychart.jpg)